apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      Hello:
        type: string
        default: sad
  push:
    branches:
      - "***"
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: choice
        options:
          - QA
          - PREPROD
          - PROD
        default: QA
        required: true
        description: Choose the environment
      TAG:
        type: string
        description: Enter the test annotated tags
jobs:
  build:
    steps:
      - name: Git checkout
        uses: https://github.com/cloudbees-io/checkout@v1
        with:
          fetch-depth: 1
      - name: CB - Context
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo $PATH
          echo ${{ cloudbees.api.url }}
          cat /etc/*release*
          echo ${{ cloudbees.scm.sha }}
          echo ${{ cloudbees.scm.branch }}
          echo ${{ cloudbees.run_id }}
          echo ${{ cloudbees.scm.ref }}
          echo ${{ cloudbees.scm.token }}
          echo ${{ cloudbees.event_name }}
          echo "Test ENVIRONMENT $ENVIRONMENT"
          echo "Test TAG: $TAG"
          echo "Smoke|FM|ActionTest" | sed 's/\([A-Za-z0-9_]*\)/@\1/g'

      - name: GGet terminal details
        uses: docker://mcr.microsoft.com/playwright:v1.49.0-noble
        run: |
            echo $SHELL
            pstree -p | grep -i terminal
          
      - name: Git Details
        uses: docker://mcr.microsoft.com/playwright:v1.49.0-noble
        shell: sh
        run: |
          git log -n 5 --oneline
          export COMMIT_ID=$(git log --pretty=format:"%H _ %an <%ae> _ %s" | awk -F _ '{print $1}')
          export AUTHOR=$(git log --pretty=format:"%H _ %an <%ae> _ %s" | awk -F _ '{print $2}')
          export MESSAGE=$(git log --pretty=format:"%H _ %an <%ae> _ %s" | awk -F _ '{print $3}')
          echo $AUTHOR
          echo $COMMIT_ID
          echo $MESSAGE
          echo $SHELL
          pstree -p | grep -i terminal

      - name: If else
        uses: docker://mcr.microsoft.com/playwright:v1.49.0-noble
        shell: sh
        env:
          CI_BRANCH: ${{ cloudbees.scm.branch }}
        run: |
          
          if [ "${{ cloudbees.event_name }}" = "push" ] && [ "$CI_BRANCH" != "main" ]; then
            ENV=$(git log --pretty=format:"%H _ %an <%ae> _ %s" | head -n 1 | awk -F _ '{print $3}' | awk -F'[][]' '{print $2}')
            TAG=$(git log --pretty=format:"%H _ %an <%ae> _ %s" | head -n 1 | awk -F _ '{print $3}' | awk -F'[][]' '{print $4}')
            echo "Environment: $ENV"
            echo "TAG: $TAG"
          else
            echo  " The push event is ${{ cloudbees.event_name }}"
          fi
