apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo $PATH
          echo ${{ cloudbees.api.url }}
          cat /etc/*release*
          echo ${{ cloudbees.scm.sha }}
          echo ${{ cloudbees.scm.branch }}
          echo ${{ cloudbees.scm.committer}}
          echo ${{ cloudbees.run_id }}