apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Git checkout
        uses: https://github.com/cloudbees-io/checkout@v1
        with:
          fetch-depth: 1
        
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo $PATH
          echo ${{ cloudbees.api.url }}
          cat /etc/*release*
          echo ${{ cloudbees.scm.sha }}
          echo ${{ cloudbees.scm.branch }}
          echo ${{ cloudbees.run_id }}
          echo ${{ cloudbees.scm.ref }}
          echo ${{ cloudbees.scm.token }}
      - name: Say hello
        uses: docker://mcr.microsoft.com/playwright:v1.49.0-noble
        shell: sh
        run: |
          export COMMIT_ID= $(git log --pretty=format:"%H _ %an <%ae> _ %s" | awk -F _ '{print $1}')
          export AUTHOR= $(git log --pretty=format:"%H _ %an <%ae> _ %s" | awk -F _ '{print $2}')
          export MESSAGE= $(git log --pretty=format:"%H _ %an <%ae> _ %s" | awk -F _ '{print $3}')
          echo $AUTHOR
          echo $COMMIT_ID
          echo $MESSAGE
