apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
      - name: checkout
        uses: https://github.com/cloudbees-io/checkout@v1
  
      - name: scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        kind: scan
        with:
          language: PYTHON
