apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  scans:
    steps:
      - name: scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        kind: scan
        with:
          language: PYTHON

  build:
    needs: [ scans ]
    steps:
      - name: checkout
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Build project and Run tests for Python App
        uses: docker://python:3.11.3-bullseye
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pytest tests/
  
      
